GET http://localhost:3000/products

####
GET http://localhost:3000/products/2

####

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "x3",
    "brand": "samsang",
    "description": "true"
}

####
PUT http://localhost:3000/products/2
Content-Type: application/json

{
    "name": "x55",
    "brand": "samsang",
    "description": "true"
}

####

DELETE http://localhost:3000/products/2